config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'eateries/new'
  post 'eateries/create'
  get 'lunch/go' # => "lunch#go"
  root 'lunch#go'
  get '/login', to:'sessions#new'
  post 'sessions/create'
  delete '/logout', to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eatery.rb
class Eatery < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !session[:user_id].nil?
  end
end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController

  before_action :login_required

  def new
  end
  def create
    eatery = Eatery.new(eatery_params)
    eatery.save
    flash[:success] = "#{eatery.name}を追加しました"
    redirect_to root_path
  end

  private

  def eatery_params
    params.require(:eatery).permit(:name)
  end

  def user_params
    params.requre(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def login_required
    redirect_to login_path unless current_user
  end

end

app/controllers/lunch_controller.rb
class LunchController < ApplicationController
  def go
    eataries = Eatery.all
    @recommend = eataries.sample
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = 'ログインしました'
      redirect_to root_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/lunch_helper.rb
module LunchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/eateries/new.html.erb
<%= form_with model: Eatery.new, url: {action: :create}, local: true do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, id: 'eatery_name' %>
</div>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where2eat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class ="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete %>
      <%  else %>
        <%= link_to "Log in", login_path %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/lunch/go.html.erb
<h3>今日のランチは……</h3>
<h1><%= @recommend.name %></h1>
<h2><%= @recommend.product %></h2>
<h3>住所：<%= @recommend.address %></h3>
<h3>TEL：<%= @recommend.tel %></h3>
<h3>開店時間：<%= @recommend.open %> 〜 <%= @recommend.close %></h3>